### ISSUE TITLE
Missing nib import

### ISSUE THREAD

**Issue by fsquaredmedia** [raulghm/Font-Awesome-Stylus#14]
When I try to run gulp serve I get an error. Looks likes there is a reference to nib however there is no nib.styl or directory in the vendor package. I can comment it out and it works. 

{ [Error: ~/myproject/node_modules/font-awesome-stylus/stylus/font-awesome.styl:6:9

    6| @import "nib"

failed to locate @import file nib.styl

**Comment by kane-c** [comment]
nib is no longer required as of v4.3.0.

**Comment by bevacqua** [comment]
@raulghm Can you please bump this package on npm? Still throwing issues on nib

**Comment by PhilT** [comment]
@bevacqua npm package updated. Cheers, Phil
