### ISSUE TITLE
path.styl not compiling properly

### ISSUE THREAD

**Issue by duanearnett** [raulghm/Font-Awesome-Stylus#20]
Line 8 of path.styl:
```
url('#{$fa-font-path}/fontawesome-webfont.woff2?v=#{$fa-version}') format('woff2'), \
```
doesn't seem to compile properly and comes up as a missing resource when served.

Changing to:
```
url($fa-font-path + '/fontawesome-webfont.woff2?v=' + $fa-version) format('woff2'), \
```
works fine.

Is there something I'm missing?

**Comment by duanearnett** [comment]
Okay - there is. 

Clearing bower cache, deleting locally, and reinstalling, it appears the version in bower is 1.2.0, even though it should be 4.3.0.

**Comment by raulghm** [comment]
Yes dude, clear cache and reinstall again :)
