### ISSUE TITLE
Change directory structure

### ISSUE THREAD

**Issue by neysimoes** [raulghm/Font-Awesome-Stylus#31]
Hi!
We can change directory structure to simplify font-awesome-stylus usage.

```bash
$ npm install font-awesome-stylus
```
Example of requiring and using font-awesome middleware to create compile function to utilize in other frameworks.

```javascript
var fontAwesome = require('font-awesome-stylus'),
    stylus    = require('stylus');

function compile(str) {
  return stylus(str)
    .use(fontAwesome());
}
```
To import whole font-awesome in your stylus file:
```stylus
@import "font-awesome"
```
---
We need change `stylus` folder name to `font-awesome` and add a simple `index.js` file with:
```javascript
exports = module.exports = function () {
  return function(style){
    style.include(__dirname);
  }
}
```

And add `"main": "index.js"` on `package.json`.

**Comment by raulghm** [comment]
@neysimoes Excellent proposal!

Let me a time for make tests and accept you PR ;)

**Comment by raulghm** [comment]
Hi @neysimoes recently I added a alpha version `4.7.1-alpha.1` with you new structure and other improves to make more compatible this package, could you test this last version please?

**Comment by neysimoes** [comment]
@raulghm I have tested and the project entry point is wrong.

change `"main": "index.js"` to `"main": "lib/font-awesome-stylus.js"` on package.json

**Comment by neysimoes** [comment]
https://github.com/raulghm/Font-Awesome-Stylus/pull/33
